### ISSUE TITLE
How to deal with query parameters?

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/amazon-cloudfront-signed-urls-using-lambda-secretsmanager#5]
Somewhere in the cloudfront architecture settings is inclusion (really  a requirement) for query parameters but I can't identify where.  I am using this code in the context of a step functions state machine to pass a s3 stored pdf file URL .  I don't need query parameters but my lambda tests fail if I don't include any.  I can add some placeholders but would prefer to pass the pure file referenced URL.  Welcome any insights, tips after scouring Google, SO.  TIA.

**Comment by leskchan** [comment]
Hi Vince (weisisheng),

First I want to apologize for this late response to your question.

In this sample, Amazon CloudFront is configured to accept query parameters but they are NOT required. Your events for the canned example would be like these:

With Query Parameters:
{
  "baseUrl": "https://d1h40r1bnjoja0.cloudfront.net/sample.html?q1=123&q2=abc",
  "expiration": "12/12/2021 12:30:30 EST"
}

Without Query Parameters:
{
  "baseUrl": "https://d1h40r1bnjoja0.cloudfront.net/sample.html?", // Note the ? at the end
  "expiration": "12/12/2021 12:30:30 EST"
}

Also I'm in the process of updating the sample code to not requiring the use of AWS Root to create CF Public Key. See [Amazon CloudFront announces support for public key management through IAM user permissions for signed URLs and signed cookies](https://aws.amazon.com/about-aws/whats-new/2020/10/cloudfront-iam-signed-url/).

Thanks,
Les

**Comment by leschan** [comment]
Hi Vince (weisisheng),

First I want to apologize for this late response to your question.

In this sample, Amazon CloudFront is configured to accept query parameters but they are NOT required. Your events for the canned example would be like these:

With Query Parameters:
{
"baseUrl": "https://d1h40r1bnjoja0.cloudfront.net/sample.html?q1=123&q2=abc",
"expiration": "12/12/2021 12:30:30 EST"
}

Without Query Parameters:
{
"baseUrl": "https://d1h40r1bnjoja0.cloudfront.net/sample.html?", // Note the ? at the end
"expiration": "12/12/2021 12:30:30 EST"
}

Also I'm in the process of updating the sample code to not requiring the use of AWS Root to create CF Public Key. See [Amazon CloudFront announces support for public key management through IAM user permissions for signed URLs and signed cookies](https://aws.amazon.com/about-aws/whats-new/2020/10/cloudfront-iam-signed-url/).

Thanks,
Les
