### ISSUE TITLE
access denined 

### ISSUE THREAD

**Issue by ManuXavier43** [aws-samples/amazon-cloudfront-signed-urls-using-lambda-secretsmanager#8]
i have done all the steps and when i use the custom signed url and put it in my browser i get the error This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>

**Comment by leschan** [comment]
Hi ManuXavier43,

This is the sample test event in the repo

{
  "baseUrl": "https://d1hxxxxxxxxxx.cloudfront.net/sample.html?q1=123&q2=abc",
  "expiration": "12/07/2021 12:30:30 EST",
  "startDateTime": "12/07/2020 05:00:05 PST",
  "allowedIpAddress": "0.0.0.0/0"
}

Did you change, at minimum, the expiration date pass 12/07/2021? 

If it still doesn't work, please share your test event.

Thanks,
Les

**Comment by ManuXavier43** [comment]
Hey les 
i did change the test values this is the current test event i am using
{
  "baseUrl": "https://d1x6e77q68wxy3.cloudfront.net/assets/Leadershipprinciples/MP4/Leadershipprinciples.mp4",
  "expiration": "25/06/2025 19:50:00 GMT",
  "startDateTime": "25/06/2024 14:40:00 GMT",
  "allowedIpAddress": "0.0.0.0/0"
}
thanks for the quick reply
Thanks,
Manu

**Comment by ManuXavier43** [comment]
Hey les 
i did change the test values this is the current test event i am using
{
  "baseUrl": "https://d1x6e77q68wxy3.cloudfront.net/assets/Leadershipprinciples/MP4/Leadershipprinciples.mp4",
  "expiration": "25/06/2025 19:50:00 GMT",
  "startDateTime": "25/06/2024 14:40:00 GMT",
  "allowedIpAddress": "0.0.0.0/0"
}
thanks for the quick reply
Thanks,
Manu

**Comment by leschan** [comment]
HI Manu,

Your date format is incorrect. Please change from "DD/MM/YYYY" to "MM/DD/YYYY".

Please note that this test event is just how I implemented the code in getting information and has nothing do with CloudFront. You can design your own test event and modify the code to process the event accordingly.

Thanks,
Les

**Comment by ManuXavier43** [comment]
Thank you so much for the help,
i will do i wanted to use your code to get a understanding of how all the services worked 
thanks again 
Manu
